services:
  postgresdb:
    image: postgres:11
    container_name: blog_db
    restart: always
    environment:
      - POSTGRES_USER=${{ secrets.DB_USER }} 
      - POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
      - POSTGRES_DB=${{ secrets.DB_NAME }}
    ports:
      - "5432:5432"
    volumes:
      - ./api-rest-ezops/database/create.sql:/docker-entrypoint-initdb.d/create.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  node-server:
    image: matheusmello09/nodejs-api:latest
    container_name: api_rest
    restart: always
    environment:
      - DB_USER=${{ secrets.DB_USER }}  
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      - DB_HOST=postgresdb
      - DB_NAME=${{ secrets.DB_NAME }}
    ports:
      - "4000:4000"
    command: ["node", "server/server.js"]
    networks:
      - app-network
    depends_on:
      - postgresdb

  vue-app:
    image: matheusmello09/vue-js:latest
    container_name: vue-app
    restart: always
    ports:
      - "80:3000"
    networks:
      - app-network
    depends_on:
      - node-server

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
