services:
  postgresdb:
    image: matheusmello09/postgres-with-schema:latest
    container_name: postgresql
    restart: always
    # environment:
    #   POSTGRES_USER: ${DB_USER} 
    #   POSTGRES_PASSWORD: ${DB_PASSWORD}
    #   POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      # - ./api-rest-ezops/database/create.sql:/docker-entrypoint-initdb.d/create.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  node-server:
    image: matheusmello09/nodejs-api
    container_name: api_node
    restart: always
    env_file: ".env"
    environment:
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgresdb
      DB_NAME: ${DB_NAME}
    ports:
      - "4000:4000"
    command: ["node", "server/server.js"]
    networks:
      - app-network
    depends_on:
      - postgresdb

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
