services:
  postgresdb:
    image: matheusmello09/postgres:latest
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 928BDeuE
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      # - ./matheus-api-rest-ezops/database/create.sql:/docker-entrypoint-initdb.d/create.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  node-server:
    image: matheusmello09/nodejs-api:latest
    container_name: api_node
    restart: always
    environment:
      DB_USER: root
      DB_PASSWORD: 928BDeuE
      DB_HOST: postgresdb
      DB_NAME: blog
    ports:
      - "4000:4000"
    command: ["node", "server/server.js"]
    networks:
      - app-network
    depends_on:
      - postgresdb

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
