apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api-service
  template:
    metadata:
      labels:
        app: node-api-service
    spec:
      containers:
      - name: node-api-service
        image: matheusmello09/nodejs-api:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "928BDeuE"
        - name: DB_HOST
          value: "postgresdb-service"
        - name: DB_NAME
          value: "blog"
        - name: API_PORT
          value: "4000"
        command: ["node", "server/server.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  selector:
    app: node-api-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 31080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.nodejs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-api-service
            port:
              number: 4000
      - path: /posts
        pathType: Prefix
        backend:
          service:
            name: node-api-service
            port:
              number: 4000