apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app
        image: matheusmello09/vue-js:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  ports:
  - port: 3000
    targetPort: 80
  selector:
    app: vue-app
  type: LoadBalancer
