apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app
        image: matheusmello09/vue-js:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  selector:
    app: vue-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue-app-ingress
spec:
  rules:
  - host: test-matheus.exam.ezopscloud.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vue-app-service
            port:
              number: 80
